export const COLORS = {
  bg: "#0A0A0F",
  surface: "#111118",
  surface2: "#1A1A24",
  border: "#2A2A3A",
  blue: "#2563EB",
  blueLight: "#3B82F6",
  gold: "#F59E0B",
  goldLight: "#FCD34D",
  text: "#F1F5F9",
  textMuted: "#64748B",
  success: "#10B981",
  danger: "#EF4444",
} as const;

export const BIRDS = [
  {
    id: "falcon",
    name: "الصقر",
    nameEn: "Falcon",
    emoji: "🦅",
    audience: "الجميع",
    symbol: "السرعة والحدة",
    unlock: "مجاني — افتراضي",
    plan: "free",
    style: "مختصر وحاد، لا مجاملات",
    color: "#2563EB",
    messages: {
      sessionStart: "خل الجوال يستنى. أنا أستنى نتائجك.",
      sessionEnd: "50 دقيقة خلصت. كيف حسيت؟",
      streakBreak: null,
      wrongAnswer: "هذا راح يدخل الخزنة. ما تغلط فيه مرتين.",
      highScore: "قلت لك.",
      absent: "كنت فين؟",
      firstLogin: "أنا رفيقك من هنا للنتيجة — اختر مهمتك.",
    },
  },
  {
    id: "hoopoe",
    name: "الهدهد",
    nameEn: "Hoopoe",
    emoji: "🦜",
    audience: "بنات",
    symbol: "الذكاء والبصيرة",
    unlock: "شاهين",
    plan: "shaheen",
    style: "حكيم، يسأل",
    color: "#8B5CF6",
    messages: {
      sessionStart: "عقلك صافي اليوم؟ خلّنا نبدأ.",
      sessionEnd: "ليش غلطت هنا؟ فكر.",
      streakBreak: null,
      wrongAnswer: "ليش غلطت هنا؟ فكر.",
      highScore: "علمت أنك قادرة.",
      absent: "متى رح تبدئين؟",
      firstLogin: "الحكمة في الصبر. هيا.",
    },
  },
  {
    id: "swan",
    name: "البجعة",
    nameEn: "Swan",
    emoji: "🦢",
    audience: "بنات",
    symbol: "الجمال والصبر",
    unlock: "شاهين",
    plan: "shaheen",
    style: "هادئة صبورة",
    color: "#06B6D4",
    messages: {
      sessionStart: "تنفسي، ركّزي، ابدئي.",
      sessionEnd: "عادي، كل خطأ خطوة.",
      streakBreak: null,
      wrongAnswer: "عادي، كل خطأ خطوة.",
      highScore: "رأيت؟ الصبر ثمر.",
      absent: "الطريق ما اختفى، فقط انتِ توقفتِ.",
      firstLogin: "أنا معك في كل خطوة.",
    },
  },
  {
    id: "raven",
    name: "الغراب",
    nameEn: "Raven",
    emoji: "🐦‍⬛",
    audience: "أولاد",
    symbol: "الذكاء والغموض",
    unlock: "شاهين",
    plan: "shaheen",
    style: "ساخر لطيف",
    color: "#6366F1",
    messages: {
      sessionStart: "هيا نشوف قد إيش تصمد.",
      sessionEnd: "أوه، خلصت؟ ما توقعت.",
      streakBreak: null,
      wrongAnswer: "أوه، هذا السؤال مرة ثانية؟",
      highScore: "مرة مو بطال.",
      absent: "اختفيت ولا إيش؟",
      firstLogin: "يلا نشوف.",
    },
  },
  {
    id: "peacock",
    name: "الطاووس",
    nameEn: "Peacock",
    emoji: "🦚",
    audience: "أولاد",
    symbol: "الطموح",
    unlock: "شاهين",
    plan: "shaheen",
    style: "تنافسي",
    color: "#10B981",
    messages: {
      sessionStart: "فلان تجاوزك أمس. وش تسوي اليوم؟",
      sessionEnd: "ما كافي. ارجع بكرة بجهد أكثر.",
      streakBreak: null,
      wrongAnswer: "المنافسين ما غلطوا هنا.",
      highScore: "هذا هو. الطموح يثمر.",
      absent: "فلان من الرياض تجاوزك — وش تسوي؟",
      firstLogin: "مرحبا بالطموح.",
    },
  },
  {
    id: "phoenix",
    name: "الفينكس",
    nameEn: "Phoenix",
    emoji: "🔥",
    audience: "النخبة",
    symbol: "البعث والنخبة",
    unlock: "عنقاء فقط",
    plan: "anqa",
    style: "أسطوري، نادر الكلام",
    color: "#F59E0B",
    messages: {
      sessionStart: "من رماد الإهمال يولد التفوق.",
      sessionEnd: "لحظة تاريخية.",
      streakBreak: null,
      wrongAnswer: "الفينكس يحترق ليولد من جديد.",
      highScore: "هذا هو درب النخبة.",
      absent: "النار تخمد بالإهمال.",
      firstLogin: "أنت من النخبة. أثبت ذلك.",
    },
  },
] as const;

export const PLANS = [
  {
    id: "free",
    name: "مجاني",
    price: 0,
    period: "",
    badge: "",
    color: "#64748B",
    features: [
      "خزنة الأخطاء (20 سؤال)",
      "3 دروس تأسيسية تجريبية",
      "تايمر Orbit 50/10",
      "الخريطة التفاعلية",
      "Daily Streak",
      "المجلس (قراءة فقط)",
    ],
    missing: ["خزنة غير محدودة", "كل دروس التأسيس", "المجلس (مشاركة)", "الأرينا"],
  },
  {
    id: "shaheen",
    name: "شاهين",
    price: 35,
    period: "شهر",
    badge: "الأكثر شيوعاً",
    color: "#2563EB",
    features: [
      "خزنة الأخطاء غير محدودة",
      "كل دروس التأسيس",
      "بنك المراجعة الذكية SM-2",
      "المجلس (مشاركة كاملة)",
      "الأرينا 1v1",
      "5 طيور للاختيار",
      "تحليل الأداء الأسبوعي",
    ],
    missing: [],
  },
  {
    id: "anqa",
    name: "عنقاء",
    price: 119,
    period: "سنة",
    priceLifetime: 209,
    badge: "النخبة والمؤسسون",
    color: "#F59E0B",
    features: [
      "كل مميزات شاهين",
      "الفينكس (الطائر الأسطوري)",
      "شهادة الانضباط الرقمية",
      "خصم 79 ريال عند الانتقال للجامعة",
      "دور المؤسس الدائم",
      "أولوية في الميزات الجديدة",
    ],
    missing: [],
  },
] as const;

export const PARENT_PLAN = {
  id: "sand",
  name: "سند",
  price: 49,
  period: "شهر",
  color: "#10B981",
  badge: "لولي الأمر",
  features: [
    "حالة الابن في الوقت الفعلي",
    "تقارير أداء أسبوعية",
    "مقارنة بالمتوسط العام",
    "رسائل دعم بعد الجلسة",
    "إضافة ابن واحد مجاناً",
    "خصم 50% لأخ أو أخت",
  ],
};

export const SUBJECTS = ["فيزياء", "رياضيات", "كيمياء", "أحياء"] as const;

export const RAKAN_SCHEDULE = {
  فيزياء: [
    { day: 1, lesson: "علم الفيزياء", hours: 1, pages: "8-10", difficulty: "متوسط", progress: 4 },
    { day: 2, lesson: "الميكانيكا (1)", hours: 3, pages: "11-19", difficulty: "متوسط", progress: 14 },
    { day: 3, lesson: "الميكانيكا (2)", hours: 3, pages: "20-27", difficulty: "متوسط", progress: 24 },
    { day: 4, lesson: "الطاقة", hours: 2, pages: "28-34", difficulty: "متوسط", progress: 33 },
    { day: 5, lesson: "حالات المادة", hours: 2, pages: "35-40", difficulty: "متوسط", progress: 40 },
    { day: 6, lesson: "الموجات والصوت", hours: 3, pages: "41-45", difficulty: "متوسط", progress: 46 },
    { day: 7, lesson: "الضوء", hours: 3, pages: "46-53", difficulty: "متوسط", progress: 55 },
    { day: 8, lesson: "الكهرباء (1)", hours: 3, pages: "54-60", difficulty: "متوسط", progress: 64 },
    { day: 9, lesson: "الكهرباء (2)", hours: 3, pages: "61-66", difficulty: "متوسط", progress: 71 },
    { day: 10, lesson: "المغناطيسية والكهرومغناطيسية", hours: 2, pages: "67-73", difficulty: "سهل", progress: 80 },
    { day: 11, lesson: "الفيزياء الحديثة", hours: 3, pages: "74-83", difficulty: "متوسط", progress: 92 },
    { day: 12, lesson: "الفيزياء النووية", hours: 2, pages: "84-90", difficulty: "سهل", progress: 100 },
  ],
  رياضيات: [
    { day: 1, lesson: "المنطق الرياضي والهندسة", hours: 4, pages: "92-96", difficulty: "متوسط", progress: 7 },
    { day: 1, lesson: "المثلثات والمضلعات", hours: 4, pages: "97-100", difficulty: "متوسط", progress: 12 },
    { day: 2, lesson: "الأشكال الرباعية والتشابه", hours: 4, pages: "101-107", difficulty: "متوسط", progress: 20 },
    { day: 2, lesson: "الدائرة", hours: 4, pages: "108-110", difficulty: "متوسط", progress: 23 },
    { day: 3, lesson: "الدوال والمتباينات والمصفوفات", hours: 4, pages: "111-115", difficulty: "متوسط", progress: 28 },
    { day: 3, lesson: "كثيرات الحدود ودوالها", hours: 4, pages: "116-121", difficulty: "متوسط", progress: 35 },
    { day: 4, lesson: "الدوال العكسية والجذرية والنسبية", hours: 3, pages: "122-129", difficulty: "متوسط", progress: 44 },
    { day: 5, lesson: "المتتابعات والمتسلسلات", hours: 3, pages: "130-134", difficulty: "سهل", progress: 50 },
    { day: 6, lesson: "الاحتمالات والإحصاء", hours: 3, pages: "135-141", difficulty: "متوسط", progress: 58 },
    { day: 7, lesson: "حساب المثلثات", hours: 3, pages: "142-147", difficulty: "متوسط", progress: 65 },
    { day: 8, lesson: "تحليل الدوال والتحويلات الهندسية", hours: 3, pages: "148-152", difficulty: "متوسط", progress: 71 },
    { day: 8, lesson: "الدوال الأسية واللوغاريتمية", hours: 3, pages: "153-157", difficulty: "متوسط", progress: 77 },
  ],
  كيمياء: [
    { day: 1, lesson: "مقدمة في علم الكيمياء", hours: 3, pages: "180-187", difficulty: "متوسط", progress: 10 },
    { day: 2, lesson: "نظريات الذرة والجدول الدوري", hours: 4, pages: "188-196", difficulty: "متوسط", progress: 20 },
    { day: 3, lesson: "قوى التجاذب والروابط", hours: 3, pages: "197-205", difficulty: "متوسط", progress: 31 },
    { day: 4, lesson: "الحساب الكيميائي", hours: 4, pages: "206-215", difficulty: "متوسط", progress: 43 },
    { day: 5, lesson: "سرعة التفاعل والاتزان الكيميائي", hours: 2, pages: "216-222", difficulty: "متوسط", progress: 51 },
    { day: 6, lesson: "المخاليط والمحاليل", hours: 2, pages: "223-228", difficulty: "متوسط", progress: 58 },
    { day: 7, lesson: "الأحماض والقواعد", hours: 2, pages: "229-235", difficulty: "متوسط", progress: 67 },
    { day: 8, lesson: "الكيمياء الكهربائية", hours: 2, pages: "236-241", difficulty: "متوسط", progress: 74 },
    { day: 9, lesson: "الهيدروكربونات", hours: 2, pages: "242-248", difficulty: "متوسط", progress: 82 },
    { day: 10, lesson: "مشتقات الهيدروكربونات", hours: 3, pages: "249-258", difficulty: "متوسط", progress: 94 },
    { day: 11, lesson: "المركبات العضوية الحيوية", hours: 3, pages: "259-263", difficulty: "متوسط", progress: 100 },
  ],
  أحياء: [
    { day: 1, lesson: "مقدمة في علم الأحياء", hours: 3, pages: "266-269", difficulty: "متوسط", progress: 5 },
    { day: 1, lesson: "التصنيف الحديث", hours: 3, pages: "270-273", difficulty: "متوسط", progress: 9 },
    { day: 1, lesson: "الطلائعيات والفطريات", hours: 3, pages: "274-278", difficulty: "متوسط", progress: 15 },
    { day: 2, lesson: "المملكة الحيوانية (اللافقاريات)", hours: 3, pages: "279-286", difficulty: "متوسط", progress: 24 },
    { day: 2, lesson: "المملكة الحيوانية (الفقريات)", hours: 3, pages: "287-294", difficulty: "متوسط", progress: 33 },
    { day: 3, lesson: "أجهزة جسم الإنسان", hours: 4, pages: "295-315", difficulty: "متوسط", progress: 57 },
    { day: 4, lesson: "المملكة النباتية", hours: 2, pages: "316-320", difficulty: "متوسط", progress: 63 },
    { day: 4, lesson: "الخلية", hours: 2, pages: "321-329", difficulty: "متوسط", progress: 74 },
    { day: 5, lesson: "الوراثة", hours: 4, pages: "330-338", difficulty: "متوسط", progress: 84 },
    { day: 5, lesson: "علم البيئة", hours: 4, pages: "339-347", difficulty: "متوسط", progress: 94 },
    { day: 5, lesson: "التنوع الحيوي وسلوك الحيوان", hours: 4, pages: "348-353", difficulty: "متوسط", progress: 100 },
  ],
};

export const ROADMAP_STAGES = [
  { id: "foundation", name: "التأسيس", icon: "🏗️", range: [0, 25] },
  { id: "building", name: "البناء", icon: "🧱", range: [25, 50] },
  { id: "reinforcement", name: "التعزيز", icon: "⚡", range: [50, 75] },
  { id: "finale", name: "الختام", icon: "🏆", range: [75, 100] },
] as const;

export const ERROR_CATEGORIES = [
  "استعجلت",
  "ما فهمت المفهوم",
  "خطأ حسابي",
  "نسيت القانون",
  "أخطأت في القراءة",
  "غير مصنف",
] as const;
